# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: "http://mistydawncarmichael.com"
title: Misty Dawn Carmichael
email: mistydawncarmichael@gmail.com
author: Misty Dawn
description: > # "Misty Dawn Carmichael"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
